import "./globals.scss";
import { Montserrat, Noto_Sans_JP } from "next/font/google";
import Header from "../component/Navbar/navbar";
import "ress";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  display: "swap",
});
const noto_sans_jp = Noto_Sans_JP({
  subsets: ["latin"],
  variable: "--font-noto-sans-jp",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja" className={`${montserrat.variable} ${noto_sans_jp.variable}`}>
      <body>
        <Header />
        <main className="main">{children}</main>
      </body>
    </html>
  );
}
